version: "3.9"
services:
  portfolio:
    build: .
    volumes:
      - .:/django-portfolio
    ports:
      - 8000:8000
    image: portfolio:django-portfolio
    container_name: django-portfolio
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db